apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wildfly
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
      - name: wildfly
        image: kube-wildfly:1.0
        ports:
        - containerPort: 8080
        - containerPort: 9990
