apiVersion: v1
kind: Service
metadata:
  name: wildfly-svc
  labels:
    app: wildfly
spec:
  type: NodePort
  ports:
  - name: api
    port: 8080
    nodePort: 30080
  - name: admin
    port: 9990
    nodePort: 30090
  selector:
    app: wildfly
